name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      
env:
  IMAGE_NAME: playwright-github-container-registry
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} .
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}